import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>ssr vs csr</h1>
      <div>
        <Link href="/ssr">
          <button>
            <a>Click for server side rendered page</a>
          </button>
        </Link>
      </div>
      <div>
        <Link href="/csr">
          <button>
            <a>click for client side rendered page</a>
          </button>
        </Link>
      </div>
    </div>
  );
}
